version: '3'
services:
  template-db:
    image: postgres
    restart: no
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - standard-network

  akka-api:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "9090:9001"
    stdin_open: true #studie better this
    tty: true #and this too
    depends_on:
      - template-db
    networks:
      - standard-network
    command: [ "sbt", "-J-Xms256m", "-J-Xmx412m", "-J-XX:+UseG1GC", "-J-XX:MaxGCPauseMillis=100", "-J-XX:ParallelGCThreads=2", "run" ]

networks:
  standard-network:

volumes:
  pg_data: